### ISSUE TITLE
Add more documentation on filtering snapshots

### ISSUE THREAD

**Issue by simonsan** [rustic-rs/docs#84]
rustic has a few filtering options in the config file:

```toml
filter-host = ["host2"] # Default: []
filter-label = ["label1"] # Default: []
filter-tags = ["tag1,tag2"] # Default: []
filter-paths = ["path1"] # Default: no paths filter
```

(from Discord)

Actually, this is an or condition, i.e. snapshots are not filtered out if they match anything of what is the given in the array. Moreover the different filter-* are anded - if a snapshot does not satisfy any of the filters , they are sorted out.
But note, that for paths and tags it is already possible to give multiple values - and then they are anded: filter-tags=["a,b"] matches snapshots which have both "a" and "b" as tags, whereas filter-tags=["a","b"] matches snapshots which have either "a" or "b" as tag.

What is (currently) not possible is the filter exactly for a tag list or path list: A snapshot with tags "a,b,c" is currently shown when you specify filter-tags=["a,b"].

## Procedure

- affected file https://github.com/rustic-rs/docs/blob/main/src/commands/misc/filter.md
- make `Filtering snapshots to Copy` a subheading
- general headline can be Filtering Snapshots
- write above (and some more explanations) under general headline
